/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class Main {

	public static void main(String[] args) {
		System.out.println("Hola Mundo");
		Connection con;
		String url= "jdbc:mysql://localhost:6033/biblioteca";
		try {
			con = DriverManager.getConnection(url, "developer" , "programaciondaw");
		} catch (SQLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}
}
